#spring.application.name=config-server
#server.port=8888
#
##配置git仓库地址
#spring.cloud.config.server.git.uri=https://github.com/Chentaotest/springcloud.git
#
##配置仓库路径
#spring.cloud.config.server.git.searchPaths=respo
#
##配置仓库的分支
#spring.cloud.config.label=config
#
##访问git仓库的用户名和密码
#spring.cloud.config.server.git.username=418251639@qq.com
#spring.cloud.config.server.git.password=Ct05461027
#
#
#eureka.client.serviceUrl.defaultZone=http://localhost:8889/eureka/
server:
  port: 8888

spring:
  application:
    name: config-server
---
#配置git仓库地址
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chentaotest/springcloud.git
---
#配置仓库路径
spring:
  cloud:
    config:
      server:
        git:
          search-paths: respo
---
#访问git仓库的用户名和密码
spring:
  cloud:
    config:
      server:
        git:
          username: 418251639@qq.com
          password: Ct05461027

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/